[phases.setup]
nodejs = "18" # Especifica la versión de Node.js que necesitas

[phases.install]
commands = ["npm install"] # Utiliza npm install para instalar las dependencias

[phases.build]
commands = ["npm run build"] # Construye tu aplicación

[phases.start]
commands = ["npm run start"] # Inicia tu aplicación